/**
 * Utility for interacting with Google's Gemini API using direct API calls
 */

// The API key is loaded from environment variables
const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY;
const API_URL = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent';

export interface ProductCopyRequest {
  name?: string;
  category?: string;
  keywords?: string;
  tone?: 'playful' | 'professional' | 'minimal' | 'luxury' | 'casual';
}

export interface ProductCopyResult {
  name: string;
  description: string;
  features: string; // bullet points separated by newlines
  specifications: string; // bullet points separated by newlines
  tags: string; // comma-separated tags
  care_instructions: string;
  usage_guidelines: string;
}

async function callGemini(prompt: string): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error('VITE_GEMINI_API_KEY is not configured');
  }

  const response = await fetch(`${API_URL}?key=${GEMINI_API_KEY}`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      contents: [{
        parts: [{ text: prompt }],
      }],
    }),
  });

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}));
    console.error('Gemini API error:', errorData);
    throw new Error(
      `Gemini API error: ${errorData.error?.message || response.statusText || 'Unknown error'}`,
    );
  }

  const data = await response.json();
  const generatedText: string | undefined = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText) {
    throw new Error('No content generated by Gemini API');
  }

  return generatedText;
}

/**
 * Generate structured product copy (name, description, features, specs, tags, care, usage)
 * for the admin product dialogs.
 */
export async function generateProductCopy(request: ProductCopyRequest): Promise<ProductCopyResult> {
  const tone = request.tone || 'playful';
  const prompt = `
You are helping an ecommerce admin write product details.

Generate a single JSON object for a product based on this context:
- Name: ${request.name || '(none provided)'}
- Category: ${request.category || '(unspecified)'}
- Extra keywords or notes: ${request.keywords || '(none)'}
- Tone: ${tone}

Return ONLY valid JSON with these exact keys:
{
  "name": string,
  "description": string,
  "features": string,          // bullet points separated by \n
  "specifications": string,    // bullet points separated by \n
  "tags": string,              // comma-separated keywords
  "care_instructions": string,
  "usage_guidelines": string
}

Constraints:
- Keep description under 120 words.
- Use friendly, clear language.
- Do not include markdown formatting.
- Do not include backticks or code fences.
- Do not explain what you are doing.
`;

  const raw = await callGemini(prompt);

  // Attempt to parse JSON from the model output
  let jsonText = raw.trim();
  // Strip accidental code fences if present
  if (jsonText.startsWith('```')) {
    jsonText = jsonText.replace(/^```[a-zA-Z]*\n?/, '').replace(/```$/, '').trim();
  }

  try {
    const parsed = JSON.parse(jsonText) as Partial<ProductCopyResult>;
    return {
      name: parsed.name || request.name || 'New Product',
      description: parsed.description || '',
      features: parsed.features || '',
      specifications: parsed.specifications || '',
      tags: parsed.tags || '',
      care_instructions: parsed.care_instructions || '',
      usage_guidelines: parsed.usage_guidelines || '',
    };
  } catch (e) {
    console.error('Failed to parse Gemini product copy JSON, returning raw text', e, raw);
    // Fallback: use raw text as description
    return {
      name: request.name || 'New Product',
      description: raw.trim(),
      features: '',
      specifications: '',
      tags: '',
      care_instructions: '',
      usage_guidelines: '',
    };
  }
}

/**
 * Generate WhatsApp template content using Gemini AI
 * @param templateType The type of template to generate (e.g., order_confirmation)
 * @param description Brief description of the template's purpose
 * @returns Generated template content
 */
export async function generateTemplateContent(
  templateType: string,
  description: string
): Promise<string> {
  try {
    // List of available variables for templates
    const availableVariables = [
      'customerName', 'orderId', 'amount', 'retryUrl', 'carrier',
      'trackingLink', 'estimatedDelivery', 'feedbackLink', 'reviewLink',
      'refundAmount', 'daysSinceDelivery', 'reorderLink', 'cartUrl'
    ];

    // Construct the prompt for Gemini
    const prompt = `
      Create a short WhatsApp message template for a business CRM system. The template type is: ${templateType}.
      
      Template purpose: ${description}
      
      IMPORTANT FORMATTING INSTRUCTIONS:
      1. Start with 1-2 relevant emojis followed by a *bold title*
      2. Use line breaks (\n) between paragraphs
      3. Keep the message under 500 characters total
      4. Format key information with *asterisks* to make it bold in WhatsApp
      5. Use a friendly, professional tone
      6. Include a clear call-to-action if relevant
      7. DO NOT include any explanations or comments about the template
      8. ONLY return the template text itself
      
      AVAILABLE VARIABLES (use exactly as shown):
      ${availableVariables.map(v => `- {{${v}}}`).join('\n')}
      
      For the template "${templateType}", be sure to include the most relevant variables from the list above.
      
      EXAMPLE FORMAT (for a different template type):
      🎉 *Order Confirmed* 🎉\n\nHi {{customerName}},\n\nYour order #{{orderId}} has been confirmed!\n\nThank you for shopping with us.\n\nWe'll update you when your order ships.
    `;

    const generatedText = await callGemini(prompt);

    // Clean up the response to extract just the template content
    const cleanedText = generatedText.replace(/```[\s\S]*?```/g, '');

    return cleanedText.trim();
  } catch (error) {
    console.error('Error generating template with Gemini:', error);
    const err = error as any;
    throw new Error(`Failed to generate template: ${err?.message || 'Unknown error'}`);
  }
}

/**
 * Generate a description for a WhatsApp template
 * @param templateType The type of template
 * @returns Generated description
 */
export async function generateTemplateDescription(templateType: string): Promise<string> {
  try {
    const prompt = `Write a brief one-sentence description (maximum 100 characters) for a WhatsApp message template of type "${templateType}". The description should explain when this template would be sent to customers.`;

    const generatedText = await callGemini(prompt);
    return generatedText.trim();
  } catch (error) {
    console.error('Error generating template description with Gemini:', error);
    return `Template for ${templateType.replace(/_/g, ' ').toLowerCase()}`;
  }
}
